name: 'Cache Manager'
description: 'Manages caching for Nx and Playwright'

inputs:
  cache-nx:
    description: 'Whether to cache Nx'
    required: false
    default: 'true'

  cache-playwright:
    description: 'Whether to cache Playwright browsers'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Cache Nx
      if: inputs.cache-nx == 'true'
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: nx-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          nx-${{ runner.os }}-

    - name: Cache Playwright browsers
      if: inputs.cache-playwright == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}