name: 'Publish Test Report'
description: 'Publishes test reports using ctrf-io/github-test-reporter'

inputs:
  report-path:
    description: 'Path to the test report files'
    required: true
    default: './.report/*.json'
  github-token:
    description: 'GitHub Token for authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@v1
      if: always()
      with:
        report-path: ${{ inputs.report-path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
