name: Build and Test

on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 15

jobs:
  run:
    runs-on: arc-runner-set
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Lint on Affected Files
        run: pnpm exec nx affected -t lint
        continue-on-error: false

      - name: Run Unit Tests on Affected Files
        run: pnpm exec nx affected -t test -c ci
        continue-on-error: false

      - name: Build Affected Projects
        run:
            pnpm exec nx affected -t build -c production
        continue-on-error: false

      - name: Publish Test Report
        uses: ./.github/actions/publish-report
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}



      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 1