name: CI Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/build-test.yml

  pr-preview:
    needs: [build-and-test]
    if: always()  # This ensures cleanup runs even if build is skipped
    uses: ./.github/workflows/pr-preview.yml