name: CI Push #Release Pipeline

on:
  push:
    branches:
      - release/*

permissions:
  actions: read
  contents: write

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test.yml

#  e2e:
#    needs: build-and-test
#    uses: ./.github/workflows/e2e.yml