name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test.yml

  e2e:
    needs: build-and-test
    uses: ./.github/workflows/e2e.yml