name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build-and-test:
    needs: setup
    uses: ./.github/workflows/build-test.yml
    with:
      cache-key: ${{ needs.setup.outputs.cache-key }}

  e2e:
    needs: [setup, build-and-test]
    uses: ./.github/workflows/e2e.yml
    with:
      cache-key: ${{ needs.setup.outputs.cache-key }}