name: CI

on:
  push:
    branches: [master, release/*]
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    uses: ./.github/workflows/build-test.yml

  preview:
    if: github.event_name == 'pull_request'
    needs: [build-and-test]
    uses: ./.github/workflows/pr-preview.yml