name: CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed


permissions:
  actions: read
  contents: write
  pull-requests: write


jobs:
  build-and-test:
    uses: ./.github/workflows/build-test.yml

  e2e:
    needs: build-and-test
    uses: ./.github/workflows/e2e.yml

  pr-preview:
    needs: build-and-test
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/pr-preview.yml