name: CI

on:
  push:
    branches: [main, release/*]
  pull_request:
    types: [opened, reopened, synchronize, closed]

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    uses: ./.github/workflows/build-test.yml

#  e2e:
#    if: github.event_name == 'pull_request'
#    needs: [build-and-test]
#    uses: ./.github/workflows/e2e.yml

  preview:
    needs: [build-and-test]  # Only require build-and-test if PR is not closed
    if: |
      github.event_name == 'pull_request' && (
        github.event.action != 'closed' ||
        needs.build-and-test.result == 'success'
      )
    uses: ./.github/workflows/pr-preview.yml