name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Lint
        run: pnpm exec nx affected -t lint


      - name: Test
        if: success()
        run: pnpm exec nx affected -t test

#      - name: Build
#        if: success()
#        run: pnpm exec nx affected -t build

#      - name: Install Playwright Browsers
#        if: success()
#        run: npx playwright install --with-deps

#      - name: E2E Tests
#        if: success()
#        run: pnpm exec nx affected -t e2e


      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './.report/*.json'
          pull-request: true
          overwrite-comment: true
          template-path: './.github/templates/custom-report.hbs'
          custom-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()