name: Actions Runner Controller Demo

on:
  push:
    branches: [main, release/*]
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  Explore-GitHub-Actions:
    runs-on: arc-runner-set
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
