name: Generate SBOM

on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 30

jobs:
  cyclone-dx:
    runs-on: arc-runner-set
    timeout-minutes: ${{ inputs.timeout-minutes }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run ORT Action
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          # Run only analyzer and reporter steps to generate SBOM
          run: 'analyzer,reporter'
          
          # Generate CycloneDX report
          ort-cli-report-args: >
            -f CycloneDx
            --report-option "CycloneDx=output.file.formats=json"
            --repository-configuration-file ".ort.yml"
      
      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-reports
          path: |
            .ort/analyzer/analyzer-result.yml
            .ort/reporter/bom.cyclonedx.json
          retention-days: 30