name: E2E Tests

on:
  workflow_call:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      install-playwright: true

  run-e2e:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Run E2E Tests
        run: pnpm exec nx affected -t e2e

      - name: Publish E2E Test Report
        uses: ctrf-io/github-test-reporter@v1
        if: always()
        with:
          report-path: './.report/*.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}