name: Cleanup PR Preview

on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 5

jobs:
  cleanup:
    runs-on: arc-runner-set
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cleanup Preview
        uses: rossjrw/pr-preview-action@v1.6.0
        with:
          action: remove
          token: ${{ secrets.GITHUB_TOKEN }}