name: PR Preview
concurrency: preview-${{ github.ref }}

on:
  workflow_call:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Deploy Preview
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1.6.0
        with:
          source-dir: ./dist/etalytics/browser
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Preview
        if: github.event.action == 'closed' && !github.event.pull_request.merged
        uses: rossjrw/pr-preview-action@v1.6.0
        with:
          action: remove
          token: ${{ secrets.GITHUB_TOKEN }}