name: Deploy PR Preview

on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 5

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1.6.0
        with:
          source-dir: ./dist/etalytics/browser
          token: ${{ secrets.GITHUB_TOKEN }}